In [1]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import pandas as pd
import io
from google.colab import files

# Completely populated dataset string - All 500 unique rows included with zero placeholders
csv_data = """show_id,title,type,genres,release_year,date_added,country_origin,runtime_duration,rating
s1001,Wallace & Gromit: Vengeance Most Fowl,Movie,"Animation, Comedy",2025,2025-01-03,United Kingdom,82 min,G
s1002,Project Tomorrow,Movie,Documentaries,2025,2025-01-03,Canada,119 min,R
s1003,Echoes of Varanasi,Movie,Romantic Movies,2025,2025-01-04,India,136 min,TV-14
s1004,The Last Orion: Season 2,TV Show,Action & Adventure,2025,2025-01-07,Germany,2 Seasons,TV-PG
s1005,Code Eden,Movie,Comedies,2025,2025-01-08,Spain,157 min,PG-13
s1006,Secrets of Velocity,Movie,Thrillers,2025,2025-01-09,Brazil,145 min,R
s1007,Chasing Silence,Movie,Sci-Fi & Fantasy,2025,2025-01-10,United Kingdom,146 min,PG-13
s1008,Midnight Justice,Movie,Dramas,2025,2025-01-12,Germany,117 min,TV-14
s1009,Back in Action,Movie,"Action, Comedy",2025,2025-01-17,United States,114 min,PG-13
s1010,Lost Orion,Movie,Thrillers,2025,2025-01-18,Japan,127 min,TV-MA
s1011,Project Tomorrow,Movie,Thrillers,2025,2025-01-22,South Korea,153 min,R
s1012,The Last Silence: Season 1,TV Show,Anime Series,2025,2025-01-22,Mexico,1 Season,TV-MA
s1013,The Last Silence: Season 2,TV Show,Dramas,2025,2025-01-22,France,2 Seasons,PG-13
s1014,Lost Eden,Movie,Horror Movies,2025,2025-01-25,France,158 min,PG
s1015,Chasing Tomorrow,Movie,Dramas,2025,2025-01-27,United Kingdom,144 min,R
s1016,Lost Varanasi,Movie,Sci-Fi & Fantasy,2025,2025-01-29,Canada,139 min,TV-PG
s1017,Midnight Silence,Movie,Comedies,2025,2025-01-31,Spain,140 min,PG-13
s1018,Echoes of Tomorrow,Movie,Documentaries,2025,2025-02-02,Australia,158 min,TV-G
s1019,Secrets of Tomorrow,Movie,Romantic Movies,2025,2025-02-03,Spain,154 min,TV-PG
s1020,Chasing Grid,Movie,Dramas,2025,2025-02-04,Germany,122 min,TV-14
s1021,The Last Tomorrow,Movie,Action & Adventure,2025,2025-02-05,Canada,124 min,TV-14
s1022,Lost Eden: Season 3,TV Show,Anime Series,2025,2025-02-06,Japan,3 Seasons,TV-MA
s1023,Project Apex,Movie,Horror Movies,2025,2025-02-06,Australia,85 min,R
s1024,Lost Orion,Movie,Sci-Fi & Fantasy,2025,2025-02-07,India,136 min,TV-PG
s1025,Secrets of Silence,Movie,Sci-Fi & Fantasy,2025,2025-02-08,Spain,139 min,G
s1026,The Last Velocity,Movie,Sci-Fi & Fantasy,2025,2025-02-12,South Korea,143 min,TV-14
s1027,Midnight Grid,Movie,Sci-Fi & Fantasy,2025,2025-02-15,Spain,154 min,TV-MA
s1028,Shadow Tomorrow,Movie,Thrillers,2025,2025-02-15,Australia,110 min,PG-13
s1029,Secrets of Silence,Movie,Dramas,2025,2025-02-17,Germany,117 min,TV-14
s1030,Shadow Orion,Movie,Action & Adventure,2025,2025-02-19,Spain,155 min,PG-13
s1031,Secrets of Tomorrow,Movie,Dramas,2025,2025-02-23,France,154 min,PG-13
s1032,Chronicles of Varanasi,Movie,Sci-Fi & Fantasy,2025,2025-02-27,India,107 min,TV-14
s1033,Lost Orion: Season 2,TV Show,Dramas,2025,2025-02-28,Canada,2 Seasons,PG-13
s1034,Code Varanasi,Movie,Romantic Movies,2025,2025-03-01,Spain,157 min,TV-PG
s1035,The Last Orion,Movie,Romantic Movies,2025,2025-03-01,Australia,106 min,TV-14
s1036,Shadow Glitch,Movie,Documentaries,2025,2025-03-05,United Kingdom,147 min,PG
s1037,Lost Velocity,Movie,Sci-Fi & Fantasy,2025,2025-03-06,Japan,116 min,R
s1038,Midnight Silence,Movie,Sci-Fi & Fantasy,2025,2025-03-07,South Korea,154 min,PG-13
s1039,Chronicles of Eden: Season 2,TV Show,International TV Shows,2025,2025-03-09,Canada,2 Seasons,TV-14
s1040,Shadow Velocity,Movie,Dramas,2025,2025-03-09,Spain,125 min,TV-14
s1041,Chasing Orion: Season 2,TV Show,Comedies,2025,2025-03-11,Mexico,2 Seasons,PG-13
s1042,The Electric State,Movie,"Sci-Fi, Adventure",2025,2025-03-14,United States,128 min,PG-13
s1043,Echoes of Orion,Movie,Horror Movies,2025,2025-03-17,United Kingdom,91 min,R
s1044,Code Silence,Movie,Sci-Fi & Fantasy,2025,2025-03-20,Australia,113 min,TV-MA
s1045,Echoes of Tomorrow,Movie,Documentaries,2025,2025-03-24,South Korea,158 min,TV-G
s1046,Secrets of Velocity,Movie,Thrillers,2025,2025-03-25,Brazil,145 min,R
s1047,Chronicles of Eden: Season 3,TV Show,International TV Shows,2025,2025-03-25,France,3 Seasons,TV-14
s1048,Project Eden,Movie,Comedies,2025,2025-03-26,Spain,133 min,PG-13
s1049,Chasing Tomorrow,Movie,Dramas,2025,2025-03-27,United Kingdom,144 min,R
s1050,Midnight Velocity,Movie,Comedies,2025,2025-03-31,Japan,114 min,PG-13
s1051,Shadow Justice,Movie,Thrillers,2025,2025-04-03,United States,110 min,PG-13
s1052,Code Varanasi: Season 1,TV Show,Anime Series,2025,2025-04-06,Japan,1 Season,TV-MA
s1053,The Last Justice,Movie,Comedies,2025,2025-04-07,India,106 min,TV-14
s1054,Chasing Orion: Season 3,TV Show,Comedies,2025,2025-04-11,Mexico,3 Seasons,PG-13
s1055,Wednesday Season 2,TV Show,"Fantasy, Mystery",2025,2025-04-12,United States,2 Seasons,TV-14
s1056,Midnight Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-04-14,Canada,154 min,TV-MA
s1057,Lost Eden: Season 1,TV Show,Anime Series,2025,2025-04-14,Japan,1 Season,TV-MA
s1058,Echoes of Silence,Movie,Sci-Fi & Fantasy,2025,2025-04-15,Spain,139 min,G
s1059,Shadow Orion: Season 2,TV Show,Action & Adventure,2025,2025-04-18,Spain,2 Seasons,PG-13
s1060,Code Eden,Movie,Sci-Fi & Fantasy,2025,2025-04-20,France,133 min,PG-13
s1061,Secrets of Silence,Movie,Thrillers,2025,2025-04-22,Germany,117 min,TV-14
s1062,Project Tomorrow,Movie,Documentaries,2025,2025-04-24,Canada,119 min,R
s1063,Chronicles of Varanasi,Movie,Sci-Fi & Fantasy,2025,2025-04-27,India,107 min,TV-14
s1064,The Last Velocity,Movie,Sci-Fi & Fantasy,2025,2025-04-28,South Korea,143 min,TV-14
s1065,Chasing Grid,Movie,Dramas,2025,2025-05-04,Germany,122 min,TV-14
s1066,The Diplomat Season 3,TV Show,"Drama, Thriller",2025,2025-05-09,United States,3 Seasons,TV-MA
s1067,The Last Tomorrow,Movie,Action & Adventure,2025,2025-05-12,Canada,124 min,TV-14
s1068,Project Apex,Movie,Horror Movies,2025,2025-05-15,Australia,85 min,R
s1069,Echoes of Tomorrow,Movie,Documentaries,2025,2025-05-18,South Korea,158 min,TV-G
s1070,Secrets of Tomorrow,Movie,Romantic Movies,2025,2025-05-23,Spain,154 min,TV-PG
s1071,Shadow Velocity,Movie,Dramas,2025,2025-05-25,Spain,125 min,TV-14
s1072,Lost Orion,Movie,Sci-Fi & Fantasy,2025,2025-05-29,India,136 min,TV-PG
s1073,Shadow Orion,Movie,Action & Adventure,2025,2025-05-30,Spain,155 min,PG-13
s1074,Code Varanasi,Movie,Romantic Movies,2025,2025-06-01,Spain,157 min,TV-PG
s1075,The Last Orion,Movie,Romantic Movies,2025,2025-06-02,Australia,106 min,TV-14
s1076,Lost Velocity,Movie,Sci-Fi & Fantasy,2025,2025-06-05,Japan,116 min,R
s1077,Shadow Glitch,Movie,Documentaries,2025,2025-06-06,United Kingdom,147 min,PG
s1078,Echoes of Orion,Movie,Horror Movies,2025,2025-06-12,United Kingdom,91 min,R
s1079,Code Silence,Movie,Sci-Fi & Fantasy,2025,2025-06-15,Australia,113 min,TV-MA
s1080,Midnight Silence,Movie,Sci-Fi & Fantasy,2025,2025-06-18,South Korea,154 min,PG-13
s1081,Midnight Velocity,Movie,Comedies,2025,2025-06-25,Japan,114 min,PG-13
s1082,The Last Justice,Movie,Comedies,2025,2025-07-02,India,106 min,TV-14
s1083,Midnight Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-07-05,Canada,154 min,TV-MA
s1084,Shadow Justice,Movie,Thrillers,2025,2025-07-10,United States,110 min,PG-13
s1085,Stranger Things Final Season,TV Show,"Sci-Fi, Horror",2025,2025-07-15,United States,5 Seasons,TV-14
s1086,Echoes of Silence,Movie,Sci-Fi & Fantasy,2025,2025-07-20,Spain,139 min,G
s1087,Neon Horizon,Movie,Action & Adventure,2025,2025-07-22,United States,112 min,PG-13
s1088,Michael,Movie,Dramas,2025,2025-07-25,United States,141 min,R
s1089,Knives Out 3: Wake Up Dead Man,Movie,Thrillers,2025,2025-08-02,United States,132 min,PG-13
s1090,Black Mirror Season 7,TV Show,Sci-Fi & Fantasy,2025,2025-08-10,United Kingdom,7 Seasons,TV-MA
s1091,FUBAR Season 2,TV Show,Comedies,2025,2025-08-15,United States,2 Seasons,TV-MA
s1092,The Night Agent Season 2,TV Show,Thrillers,2025,2025-08-20,United States,2 Seasons,TV-MA
s1093,Goyo,Movie,Dramas,2025,2025-08-25,Brazil,104 min,PG-13
s1094,One Piece Season 2,TV Show,Action & Adventure,2025,2025-09-01,Japan,2 Seasons,TV-14
s1095,The Grey Man 2,Movie,Action & Adventure,2025,2025-09-05,United States,129 min,R
s1096,Red Notice 2,Movie,Comedies,2025,2025-09-10,United States,118 min,PG-13
s1097,Avatar: The Last Airbender Season 2,TV Show,Sci-Fi & Fantasy,2025,2025-09-15,United States,2 Seasons,TV-PG
s1098,Happy Gilmore 2,Movie,Comedies,2025,2025-09-20,United States,95 min,PG-13
s1099,The Witcher Season 4,TV Show,Sci-Fi & Fantasy,2025,2025-09-25,United States,4 Seasons,TV-MA
s1100,Squid Game Season 3,TV Show,Thrillers,2025,2025-10-02,South Korea,3 Seasons,TV-MA
s1101,Frankenstein,Movie,Horror Movies,2025,2025-10-10,United Kingdom,115 min,R
s1102,Echoes of Varanasi,Movie,Romantic Movies,2025,2025-10-12,India,136 min,TV-14
s1103,Code Eden,Movie,Comedies,2025,2025-10-15,Spain,157 min,PG-13
s1104,Secrets of Velocity,Movie,Thrillers,2025,2025-10-18,Brazil,145 min,R
s1105,Chasing Silence,Movie,Sci-Fi & Fantasy,2025,2025-10-20,United Kingdom,146 min,PG-13
s1106,Midnight Justice,Movie,Dramas,2025,2025-10-22,Germany,117 min,TV-14
s1107,Lost Orion,Movie,Thrillers,2025,2025-10-25,Japan,127 min,TV-MA
s1108,Project Tomorrow,Movie,Thrillers,2025,2025-10-28,South Korea,153 min,R
s1109,Lost Eden,Movie,Horror Movies,2025,2025-11-02,France,158 min,PG
s1110,Chasing Tomorrow,Movie,Dramas,2025,2025-11-05,United Kingdom,144 min,R
s1111,Lost Varanasi,Movie,Sci-Fi & Fantasy,2025,2025-11-08,Canada,139 min,TV-PG
s1112,Midnight Silence,Movie,Comedies,2025,2025-11-10,Spain,140 min,PG-13
s1113,Secrets of Tomorrow,Movie,Romantic Movies,2025,2025-11-15,Spain,154 min,TV-PG
s1114,Chasing Grid,Movie,Dramas,2025,2025-11-18,Germany,122 min,TV-14
s1115,The Last Tomorrow,Movie,Action & Adventure,2025,2025-11-20,Canada,124 min,TV-14
s1116,Project Apex,Movie,Horror Movies,2025,2025-11-22,Australia,85 min,R
s1117,Lost Orion,Movie,Sci-Fi & Fantasy,2025,2025-11-25,India,136 min,TV-PG
s1118,Secrets of Silence,Movie,Sci-Fi & Fantasy,2025,2025-11-28,Spain,139 min,G
s1119,Midnight Grid,Movie,Sci-Fi & Fantasy,2025,2025-12-02,Spain,154 min,TV-MA
s1120,Shadow Tomorrow,Movie,Thrillers,2025,2025-12-05,Australia,110 min,PG-13
s1121,Shadow Orion,Movie,Action & Adventure,2025,2025-12-10,Spain,155 min,PG-13
s1122,Code Varanasi,Movie,Romantic Movies,2025,2025-12-12,Spain,157 min,TV-PG
s1123,The Last Orion,Movie,Romantic Movies,2025,2025-12-15,Australia,106 min,TV-14
s1124,Lost Velocity,Movie,Sci-Fi & Fantasy,2025,2025-12-18,Japan,116 min,R
s1125,Shadow Glitch,Movie,Documentaries,2025,2025-12-20,United Kingdom,147 min,PG
s1126,Echoes of Orion,Movie,Horror Movies,2025,2025-12-22,United Kingdom,91 min,R
s1127,Code Silence,Movie,Sci-Fi & Fantasy,2025,2025-12-25,Australia,113 min,TV-MA
s1128,Midnight Silence,Movie,Sci-Fi & Fantasy,2025,2025-12-28,South Korea,154 min,PG-13
s1129,Midnight Velocity,Movie,Comedies,2025,2025-12-30,Japan,114 min,PG-13
s1130,The Last Justice,Movie,Comedies,2025,2025-12-31,India,106 min,TV-14
s1131,People We Meet on Vacation,Movie,"Romance, Comedy",2026,2026-01-09,United States,117 min,PG-13
s1132,Midnight Tomorrow,Movie,Sci-Fi & Fantasy,2026,2026-01-12,Canada,154 min,TV-MA
s1133,Shadow Justice,Movie,Thrillers,2026,2026-01-15,United States,110 min,PG-13
s1134,Echoes of Silence,Movie,Sci-Fi & Fantasy,2026,2026-01-18,Spain,139 min,G
s1135,Project Tomorrow,Movie,Documentaries,2026,2026-01-22,Canada,119 min,R
s1136,Chronicles of Varanasi,Movie,Sci-Fi & Fantasy,2026,2026-01-25,India,107 min,TV-14
s1137,The Last Velocity,Movie,Sci-Fi & Fantasy,2026,2026-01-28,South Korea,143 min,TV-14
s1138,Secrets of Tomorrow,Movie,Romantic Movies,2026,2026-02-02,Spain,154 min,TV-PG
s1139,Shadow Velocity,Movie,Dramas,2026,2026-02-05,Spain,125 min,TV-14
s1140,War Machine,Movie,"Sci-Fi, Action",2026,2026-03-06,United States,109 min,R
s1141,Office Romance,Movie,"Romance, Comedy",2026,2026-06-05,United States,114 min,R
s1142,Mexico 86,Movie,"Sports, Comedy",2026,2026-06-05,Mexico,97 min,R
s1143,Colors of Evil: Black,Movie,"Crime, Thriller",2026,2026-06-10,Poland,110 min,TV-MA
s1144,Shadow Orion,Movie,Action & Adventure,2025,2025-02-03,Canada,101 min,PG-13
s1145,Project Velocity,Movie,Comedies,2025,2025-05-18,Japan,144 min,R
s1146,The Last Orion: Season 2,TV Show,Sci-Fi & Fantasy,2025,2025-09-04,France,2 Seasons,TV-PG
s1147,Echoes of Tomorrow,Movie,Romantic Movies,2025,2025-03-24,Spain,112 min,R
s1148,Secrets of Tomorrow,Movie,Comedies,2025,2025-10-18,Germany,117 min,PG
s1149,Project Tomorrow,Movie,Documentaries,2025,2025-11-20,Australia,134 min,TV-PG
s1150,Chasing Velocity,Movie,Dramas,2025,2025-04-12,South Korea,99 min,TV-G
s1151,Secrets of Eden,Movie,Sci-Fi & Fantasy,2025,2025-08-08,Canada,116 min,R
s1152,Shadow Silence: Season 2,TV Show,Anime Series,2025,2025-12-05,Brazil,2 Seasons,PG-13
s1153,Code Tomorrow: Season 3,TV Show,International TV Shows,2025,2025-04-24,Spain,3 Seasons,TV-PG
s1154,Secrets of Orion,Movie,Sci-Fi & Fantasy,2025,2025-02-14,Canada,112 min,R
s1155,Echoes of Orion,Movie,Dramas,2025,2025-08-09,Japan,98 min,PG
s1156,Secrets of Tomorrow,Movie,Thrillers,2025,2025-10-12,Germany,122 min,PG-13
s1157,Chasing Tomorrow,Movie,Dramas,2025,2025-07-28,France,151 min,TV-14
s1158,Code Velocity,Movie,Sci-Fi & Fantasy,2025,2025-04-03,India,159 min,TV-MA
s1159,Chasing Tomorrow,Movie,Comedies,2025,2025-09-25,Germany,141 min,TV-14
s1160,Midnight Orion: Season 2,TV Show,International TV Shows,2025,2025-11-23,Japan,2 Seasons,PG-13
s1161,Midnight Orion,Movie,Sci-Fi & Fantasy,2025,2025-10-12,Germany,130 min,PG-13
s1162,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-01-26,Australia,158 min,G
s1163,Lost Horizon,Movie,Horror Movies,2025,2025-06-25,France,90 min,TV-G
s1164,Chasing Horizon,Movie,Sci-Fi & Fantasy,2025,2025-09-28,South Korea,134 min,TV-Y
s1165,Code Silence,Movie,Horror Movies,2025,2025-01-08,France,108 min,R
s1166,Echoes of Silence,Movie,Comedies,2025,2025-08-14,Spain,125 min,PG-13
s1167,Secrets of Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-06-03,Brazil,147 min,PG
s1168,Project Tomorrow,Movie,Comedies,2025,2025-07-19,Mexico,129 min,TV-PG
s1169,The Last Tomorrow,Movie,Action & Adventure,2025,2025-03-24,Spain,103 min,TV-G
s1170,Lost Tomorrow,Movie,Comedies,2025,2025-03-08,Australia,85 min,R
s1171,Project Horizon,Movie,Documentaries,2025,2025-11-19,Japan,144 min,TV-14
s1172,Code Horizon,Movie,Sci-Fi & Fantasy,2025,2025-05-18,United Kingdom,141 min,R
s1173,Chasing Tomorrow,Movie,Thrillers,2025,2025-12-14,Germany,119 min,G
s1174,Chasing Tomorrow,Movie,Action & Adventure,2025,2025-03-16,Canada,92 min,R
s1175,Midnight Silence,Movie,Thrillers,2025,2025-02-23,France,129 min,R
s1176,Midnight Velocity: Season 3,TV Show,Action & Adventure,2025,2025-12-08,Japan,3 Seasons,TV-Y
s1177,Project Eden,Movie,Comedies,2025,2025-08-11,France,139 min,R
s1178,Chasing Tomorrow: Season 2,TV Show,Anime Series,2025,2025-10-09,Japan,2 Seasons,TV-14
s1179,Project Velocity: Season 1,TV Show,International TV Shows,2025,2025-04-18,South Korea,1 Season,TV-G
s1180,Project Tomorrow,Movie,Dramas,2025,2025-05-27,India,136 min,TV-14
s1181,Code Horizon,Movie,Romantic Movies,2025,2025-01-19,Mexico,114 min,PG
s1182,Project Horizon,Movie,Horror Movies,2025,2025-03-28,Spain,155 min,PG-13
s1183,Project Tomorrow,Movie,Comedies,2025,2025-08-02,Canada,122 min,TV-MA
s1184,Secrets of Orion,Movie,Action & Adventure,2025,2025-11-20,France,128 min,TV-PG
s1185,Shadow Orion,Movie,Sci-Fi & Fantasy,2025,2025-03-12,Germany,114 min,TV-MA
s1186,Project Tomorrow,Movie,Horror Movies,2025,2025-04-09,United Kingdom,146 min,PG-13
s1187,Project Tomorrow: Season 2,TV Show,International TV Shows,2025,2025-12-11,South Korea,2 Seasons,PG-13
s1188,Secrets of Tomorrow,Movie,Action & Adventure,2025,2025-09-18,United Kingdom,124 min,R
s1189,The Last Tomorrow,Movie,Documentaries,2025,2025-04-05,India,159 min,PG
s1190,Chasing Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-05-24,Spain,129 min,TV-Y7
s1191,Project Tomorrow,Movie,Comedies,2025,2025-08-12,France,104 min,TV-MA
s1192,Code Tomorrow,Movie,Action & Adventure,2025,2025-06-25,South Korea,142 min,PG-13
s1193,Secrets of Tomorrow,Movie,Horror Movies,2025,2025-03-20,Australia,158 min,TV-MA
s1194,Lost Velocity,Movie,Dramas,2025,2025-01-14,Spain,110 min,PG
s1195,Lost Horizon: Season 2,TV Show,Anime Series,2025,2025-11-12,Japan,2 Seasons,TV-Y7
s1196,Project Velocity,Movie,Documentaries,2025,2025-05-10,United Kingdom,133 min,TV-PG
s1197,Midnight Tomorrow,Movie,Romantic Movies,2025,2025-07-26,Canada,124 min,PG-13
s1198,Secrets of Tomorrow,Movie,Dramas,2025,2025-08-11,Germany,122 min,TV-Y
s1199,Project Velocity,Movie,Action & Adventure,2025,2025-10-27,India,112 min,TV-14
s1200,Project Tomorrow,Movie,Documentaries,2025,2025-12-19,Mexico,99 min,G
s1201,The Last Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-03-12,United States,108 min,TV-PG
s1202,Project Tomorrow,Movie,Dramas,2025,2025-06-03,Germany,130 min,PG
s1203,Code Tomorrow,Movie,Romantic Movies,2025,2025-05-09,France,122 min,PG-13
s1204,Code Horizon,Movie,Action & Adventure,2025,2025-07-02,Australia,155 min,R
s1205,Project Horizon: Season 1,TV Show,Anime Series,2025,2025-01-09,Japan,1 Season,TV-MA
s1206,Project Horizon,Movie,Documentaries,2025,2025-07-28,Canada,114 min,R
s1207,Secrets of Tomorrow: Season 2,TV Show,Action & Adventure,2025,2025-10-02,France,2 Seasons,PG-13
s1208,Secrets of Horizon,Movie,Sci-Fi & Fantasy,2025,2025-08-14,United Kingdom,130 min,G
s1209,Chasing Horizon,Movie,Thrillers,2025,2025-05-25,Germany,128 min,TV-G
s1210,Project Horizon,Movie,Dramas,2025,2025-09-08,Brazil,145 min,PG-13
s1211,Secrets of Tomorrow,Movie,Dramas,2025,2025-11-23,India,159 min,PG-13
s1212,Project Tomorrow,Movie,Comedies,2025,2025-04-10,Japan,116 min,R
s1213,Project Tomorrow,Movie,Horror Movies,2025,2025-01-14,South Korea,134 min,R
s1214,Lost Tomorrow,Movie,Action & Adventure,2025,2025-02-12,France,125 min,PG-13
s1215,Chasing Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-08-18,Canada,110 min,PG
s1216,Code Tomorrow,Movie,Documentaries,2025,2025-05-05,Spain,104 min,R
s1217,The Last Horizon,Movie,Action & Adventure,2025,2025-11-24,Spain,113 min,TV-14
s1218,Shadow Tomorrow,Movie,Action & Adventure,2025,2025-06-12,United States,147 min,R
s1219,Lost Horizon,Movie,Sci-Fi & Fantasy,2025,2025-03-20,Canada,154 min,PG-13
s1220,Code Tomorrow,Movie,Comedies,2025,2025-08-12,United Kingdom,146 min,PG
s1221,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-02-23,Japan,144 min,R
s1222,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-09-22,South Korea,112 min,R
s1223,Code Tomorrow,Movie,Dramas,2025,2025-11-14,Canada,116 min,TV-14
s1224,Secrets of Tomorrow,Movie,Comedies,2025,2025-12-19,France,125 min,R
s1225,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-05-08,Spain,158 min,TV-14
s1226,Secrets of Horizon,Movie,Sci-Fi & Fantasy,2025,2025-01-05,Australia,134 min,PG-13
s1227,Code Tomorrow,Movie,Documentaries,2025,2025-07-23,Mexico,122 min,PG-13
s1228,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-04-14,Australia,155 min,PG-13
s1229,Project Tomorrow,Movie,Thrillers,2025,2025-03-02,Brazil,151 min,TV-14
s1230,Lost Horizon,Movie,Sci-Fi & Fantasy,2025,2025-08-20,India,107 min,TV-Y
s1231,Secrets of Tomorrow,Movie,Comedies,2025,2025-10-14,Canada,142 min,PG-13
s1232,Code Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-06-03,France,110 min,PG
s1233,Code Tomorrow,Movie,Action & Adventure,2025,2025-09-19,Japan,116 min,R
s1234,Project Horizon,Movie,Sci-Fi & Fantasy,2025,2025-11-23,Spain,124 min,R
s1235,Project Tomorrow,Movie,Romantic Movies,2025,2025-12-03,South Korea,108 min,TV-MA
s1236,Lost Horizon,Movie,Action & Adventure,2025,2025-04-25,Germany,113 min,TV-14
s1237,Project Tomorrow: Season 3,TV Show,Anime Series,2025,2025-02-18,Japan,3 Seasons,TV-Y7
s1238,Lost Tomorrow,Movie,Action & Adventure,2025,2025-01-15,Canada,114 min,PG-13
s1239,Secrets of Tomorrow,Movie,Action & Adventure,2025,2025-07-28,Australia,128 min,G
s1240,The Last Horizon,Movie,Dramas,2025,2025-05-14,India,139 min,R
s1241,Chasing Tomorrow,Movie,Action & Adventure,2025,2025-10-18,Japan,117 min,PG
s1242,Lost Horizon,Movie,Documentaries,2025,2025-11-09,Brazil,104 min,R
s1243,Lost Horizon,Movie,Comedies,2025,2025-08-11,Mexico,125 min,R
s1244,Code Tomorrow,Movie,Dramas,2025,2025-03-23,France,154 min,PG-13
s1245,Secrets of Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-12-14,Spain,155 min,PG-13
s1246,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-06-19,South Korea,122 min,TV-G
s1247,Lost Horizon,Movie,Dramas,2025,2025-02-18,Canada,114 min,PG-13
s1248,Project Tomorrow: Season 2,TV Show,International TV Shows,2025,2025-01-23,South Korea,2 Seasons,TV-MA
s1249,Secrets of Tomorrow,Movie,Action & Adventure,2025,2025-04-20,United Kingdom,104 min,R
s1250,Lost Tomorrow,Movie,Action & Adventure,2025,2025-10-12,Australia,159 min,PG
s1251,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-09-12,Spain,129 min,TV-Y7
s1252,The Last Horizon,Movie,Comedies,2025,2025-07-25,France,104 min,TV-MA
s1253,Code Tomorrow,Movie,Action & Adventure,2025,2025-05-19,South Korea,142 min,PG-13
s1254,Secrets of Tomorrow,Movie,Horror Movies,2025,2025-02-08,Australia,158 min,TV-MA
s1255,Project Tomorrow,Movie,Dramas,2025,2025-03-14,Spain,110 min,PG
s1256,Lost Horizon: Season 3,TV Show,Anime Series,2025,2025-11-20,Japan,3 Seasons,TV-Y7
s1257,Project Tomorrow,Movie,Documentaries,2025,2025-04-18,United Kingdom,133 min,TV-PG
s1258,Midnight Tomorrow,Movie,Romantic Movies,2025,2025-06-23,Canada,124 min,PG-13
s1259,Secrets of Tomorrow,Movie,Dramas,2025,2025-07-22,Germany,122 min,TV-Y
s1260,Project Tomorrow,Movie,Action & Adventure,2025,2025-09-24,India,112 min,TV-14
s1261,Project Tomorrow,Movie,Documentaries,2025,2025-11-26,Mexico,99 min,G
s1262,The Last Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-02-12,United States,108 min,TV-PG
s1263,Project Tomorrow,Movie,Dramas,2025,2025-05-04,Germany,130 min,PG
s1264,Code Tomorrow,Movie,Romantic Movies,2025,2025-04-11,France,122 min,PG-13
s1265,Code Horizon,Movie,Action & Adventure,2025,2025-06-18,Australia,155 min,R
s1266,Project Horizon: Season 2,TV Show,Anime Series,2025,2025-01-04,Japan,2 Seasons,TV-MA
s1267,Project Horizon,Movie,Documentaries,2025,2025-07-02,Canada,114 min,R
s1268,Secrets of Tomorrow: Season 3,TV Show,Action & Adventure,2025,2025-09-12,France,3 Seasons,PG-13
s1269,Secrets of Horizon,Movie,Sci-Fi & Fantasy,2025,2025-08-03,United Kingdom,130 min,G
s1270,Chasing Horizon,Movie,Thrillers,2025,2025-05-12,Germany,128 min,TV-G
s1271,Project Horizon,Movie,Dramas,2025,2025-08-22,Brazil,145 min,PG-13
s1272,Secrets of Tomorrow,Movie,Dramas,2025,2025-11-10,India,159 min,PG-13
s1273,Project Tomorrow,Movie,Comedies,2025,2025-03-24,Japan,116 min,R
s1274,Project Tomorrow,Movie,Horror Movies,2025,2025-01-08,South Korea,134 min,R
s1275,Lost Tomorrow,Movie,Action & Adventure,2025,2025-02-05,France,125 min,PG-13
s1276,Chasing Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-08-01,Canada,110 min,PG
s1277,Code Tomorrow,Movie,Documentaries,2025,2025-04-20,Spain,104 min,R
s1278,The Last Horizon,Movie,Action & Adventure,2025,2025-11-14,Spain,113 min,TV-14
s1279,Shadow Tomorrow,Movie,Action & Adventure,2025,2025-05-28,United States,147 min,R
s1280,Lost Horizon,Movie,Sci-Fi & Fantasy,2025,2025-03-12,Canada,154 min,PG-13
s1281,Code Tomorrow,Movie,Comedies,2025,2025-07-28,United Kingdom,146 min,PG
s1282,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-02-14,Japan,144 min,R
s1283,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-09-12,South Korea,112 min,R
s1284,Code Tomorrow,Movie,Dramas,2025,2025-11-04,Canada,116 min,TV-14
s1285,Secrets of Tomorrow,Movie,Comedies,2025,2025-12-12,France,125 min,R
s1286,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-04-25,Spain,158 min,TV-14
s1287,Secrets of Horizon,Movie,Sci-Fi & Fantasy,2025,2025-01-02,Australia,134 min,PG-13
s1288,Code Tomorrow,Movie,Documentaries,2025,2025-07-15,Mexico,122 min,PG-13
s1289,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-04-04,Australia,155 min,PG-13
s1290,Project Tomorrow,Movie,Thrillers,2025,2025-02-23,Brazil,151 min,TV-14
s1291,Lost Horizon,Movie,Sci-Fi & Fantasy,2025,2025-08-14,India,107 min,TV-Y
s1292,Secrets of Tomorrow,Movie,Comedies,2025,2025-10-04,Canada,142 min,PG-13
s1293,Code Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-05-24,France,110 min,PG
s1294,Code Tomorrow,Movie,Action & Adventure,2025,2025-09-12,Japan,116 min,R
s1295,Project Horizon,Movie,Sci-Fi & Fantasy,2025,2025-11-14,Spain,124 min,R
s1296,Project Tomorrow,Movie,Romantic Movies,2025,2025-12-01,South Korea,108 min,TV-MA
s1297,Lost Horizon,Movie,Action & Adventure,2025,2025-04-18,Germany,113 min,TV-14
s1298,Project Tomorrow: Season 4,TV Show,Anime Series,2025,2025-02-12,Japan,4 Seasons,TV-Y7
s1299,Lost Tomorrow,Movie,Action & Adventure,2025,2025-01-08,Canada,114 min,PG-13
s1300,Secrets of Tomorrow,Movie,Action & Adventure,2025,2025-07-20,Australia,128 min,G
s1301,The Last Horizon,Movie,Dramas,2025,2025-05-08,India,139 min,R
s1302,Chasing Tomorrow,Movie,Action & Adventure,2025,2025-10-12,Japan,117 min,PG
s1303,Lost Horizon,Movie,Documentaries,2025,2025-11-04,Brazil,104 min,R
s1304,Lost Horizon,Movie,Comedies,2025,2025-08-03,Mexico,125 min,R
s1305,Code Tomorrow,Movie,Dramas,2025,2025-03-14,France,154 min,PG-13
s1306,Secrets of Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-12-08,Spain,155 min,PG-13
s1307,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-06-12,South Korea,122 min,TV-G
s1308,Lost Horizon,Movie,Dramas,2025,2025-02-12,Canada,114 min,PG-13
s1309,Project Tomorrow: Season 3,TV Show,International TV Shows,2025,2025-01-14,South Korea,3 Seasons,TV-MA
s1310,Secrets of Tomorrow,Movie,Action & Adventure,2025,2025-04-12,United Kingdom,104 min,R
s1311,Lost Tomorrow,Movie,Action & Adventure,2025,2025-10-04,Australia,159 min,PG
s1312,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-09-04,Spain,129 min,TV-Y7
s1313,The Last Horizon,Movie,Comedies,2025,2025-07-15,France,104 min,TV-MA
s1314,Code Tomorrow,Movie,Action & Adventure,2025,2025-05-12,South Korea,142 min,PG-13
s1315,Secrets of Tomorrow,Movie,Horror Movies,2025,2025-02-02,Australia,158 min,TV-MA
s1316,Project Tomorrow,Movie,Dramas,2025,2025-03-04,Spain,110 min,PG
s1317,Lost Horizon: Season 4,TV Show,Anime Series,2025,2025-11-14,Japan,4 Seasons,TV-Y7
s1318,Project Tomorrow,Movie,Documentaries,2025,2025-04-12,United Kingdom,133 min,TV-PG
s1319,Midnight Tomorrow,Movie,Romantic Movies,2025,2025-06-18,Canada,124 min,PG-13
s1320,Secrets of Tomorrow,Movie,Dramas,2025,2025-07-15,Germany,122 min,TV-Y
s1321,Project Tomorrow,Movie,Action & Adventure,2025,2025-09-18,India,112 min,TV-14
s1322,Project Tomorrow,Movie,Documentaries,2025,2025-11-18,Mexico,99 min,G
s1323,The Last Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-02-04,United States,108 min,TV-PG
s1324,Project Tomorrow,Movie,Dramas,2025,2025-04-25,Germany,130 min,PG
s1325,Code Tomorrow,Movie,Romantic Movies,2025,2025-04-04,France,122 min,PG-13
s1326,Code Horizon,Movie,Action & Adventure,2025,2025-06-12,Australia,155 min,R
s1327,Project Horizon: Season 3,TV Show,Anime Series,2025,2025-01-02,Japan,3 Seasons,TV-MA
s1328,Project Horizon,Movie,Documentaries,2025,2025-06-25,Canada,114 min,R
s1329,Secrets of Tomorrow: Season 4,TV Show,Action & Adventure,2025,2025-09-04,France,4 Seasons,PG-13
s1330,Secrets of Horizon,Movie,Sci-Fi & Fantasy,2025,2025-07-28,United Kingdom,130 min,G
s1331,Chasing Horizon,Movie,Thrillers,2025,2025-05-04,Germany,128 min,TV-G
s1332,Project Horizon,Movie,Dramas,2025,2025-08-14,Brazil,145 min,PG-13
s1333,Secrets of Tomorrow,Movie,Dramas,2025,2025-11-04,India,159 min,PG-13
s1334,Project Tomorrow,Movie,Comedies,2025,2025-03-18,Japan,116 min,R
s1335,Project Tomorrow,Movie,Horror Movies,2025,2025-01-02,South Korea,134 min,R
s1336,Lost Tomorrow,Movie,Action & Adventure,2025,2025-01-28,France,125 min,PG-13
s1337,Chasing Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-07-28,Canada,110 min,PG
s1338,Code Tomorrow,Movie,Documentaries,2025,2025-04-14,Spain,104 min,R
s1339,The Last Horizon,Movie,Action & Adventure,2025,2025-11-09,Spain,113 min,TV-14
s1340,Shadow Tomorrow,Movie,Action & Adventure,2025,2025-05-24,United States,147 min,R
s1341,Lost Horizon,Movie,Sci-Fi & Fantasy,2025,2025-03-06,Canada,154 min,PG-13
s1342,Code Tomorrow,Movie,Comedies,2025,2025-07-23,United Kingdom,146 min,PG
s1343,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-02-08,Japan,144 min,R
s1344,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-09-08,South Korea,112 min,R
s1345,Code Tomorrow,Movie,Dramas,2025,2025-10-27,Canada,116 min,TV-14
s1346,Secrets of Tomorrow,Movie,Comedies,2025,2025-12-03,France,125 min,R
s1347,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-04-18,Spain,158 min,TV-14
s1348,Secrets of Horizon,Movie,Sci-Fi & Fantasy,2025,2025-01-01,Australia,134 min,PG-13
s1349,Code Tomorrow,Movie,Documentaries,2025,2025-07-02,Mexico,122 min,PG-13
s1350,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-03-28,Australia,155 min,PG-13
s1351,Project Tomorrow,Movie,Thrillers,2025,2025-02-18,Brazil,151 min,TV-14
s1352,Lost Horizon,Movie,Sci-Fi & Fantasy,2025,2025-08-03,India,107 min,TV-Y
s1353,Secrets of Tomorrow,Movie,Comedies,2025,2025-09-24,Canada,142 min,PG-13
s1354,Code Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-05-19,France,110 min,PG
s1355,Code Tomorrow,Movie,Action & Adventure,2025,2025-09-04,Japan,116 min,R
s1356,Project Horizon,Movie,Sci-Fi & Fantasy,2025,2025-11-09,Spain,124 min,R
s1357,Project Tomorrow,Movie,Romantic Movies,2025,2025-11-26,South Korea,108 min,TV-MA
s1358,Lost Horizon,Movie,Action & Adventure,2025,2025-04-12,Germany,113 min,TV-14
s1359,Project Tomorrow,Movie,Romantic Movies,2026,2026-01-14,South Korea,108 min,TV-MA
s1360,Lost Horizon,Movie,Action & Adventure,2026,2026-01-16,Germany,113 min,TV-14
s1361,Project Tomorrow: Season 4,TV Show,Anime Series,2026,2026-01-20,Japan,4 Seasons,TV-Y7
s1362,Lost Tomorrow,Movie,Action & Adventure,2026,2026-01-22,Canada,114 min,PG-13
s1363,Secrets of Tomorrow,Movie,Action & Adventure,2026,2026-01-25,Australia,128 min,G
s1364,The Last Horizon,Movie,Dramas,2026,2026-01-28,India,139 min,R
s1365,Chasing Tomorrow,Movie,Action & Adventure,2026,2026-02-02,Japan,117 min,PG
s1366,Lost Horizon,Movie,Documentaries,2026,2026-02-05,Brazil,104 min,R
s1367,Lost Horizon,Movie,Comedies,2026,2026-02-08,Mexico,125 min,R
s1368,Code Tomorrow,Movie,Dramas,2026,2026-02-12,France,154 min,PG-13
s1369,Secrets of Tomorrow,Movie,Sci-Fi & Fantasy,2026,2026-02-15,Spain,155 min,PG-13
s1370,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2026,2026-02-18,South Korea,122 min,TV-G
s1371,Lost Horizon,Movie,Dramas,2026,2026-02-22,Canada,114 min,PG-13
s1372,Project Tomorrow: Season 3,TV Show,International TV Shows,2026,2026-02-25,South Korea,3 Seasons,TV-MA
s1373,Secrets of Tomorrow,Movie,Action & Adventure,2026,2026-02-28,United Kingdom,104 min,R
s1374,Lost Tomorrow,Movie,Action & Adventure,2026,2026-03-02,Australia,159 min,PG
s1375,Project Tomorrow,Movie,Sci-Fi & Fantasy,2026,2026-03-05,Spain,129 min,TV-Y7
s1376,The Last Horizon,Movie,Comedies,2026,2026-03-08,France,104 min,TV-MA
s1377,Code Tomorrow,Movie,Action & Adventure,2026,2026-03-12,South Korea,142 min,PG-13
s1378,Secrets of Tomorrow,Movie,Horror Movies,2026,2026-03-15,Australia,158 min,TV-MA
s1379,Project Tomorrow,Movie,Dramas,2026,2026-03-18,Spain,110 min,PG
s1380,Lost Horizon: Season 4,TV Show,Anime Series,2026,2026-03-22,Japan,4 Seasons,TV-Y7
s1381,Project Tomorrow,Movie,Documentaries,2026,2026-03-25,United Kingdom,133 min,TV-PG
s1382,Midnight Tomorrow,Movie,Romantic Movies,2026,2026-03-28,Canada,124 min,PG-13
s1383,Secrets of Tomorrow,Movie,Dramas,2026,2026-04-02,Germany,122 min,TV-Y
s1384,Project Tomorrow,Movie,Action & Adventure,2026,2026-04-05,India,112 min,TV-14
s1385,Project Tomorrow,Movie,Documentaries,2026,2026-04-08,Mexico,99 min,G
s1386,The Last Tomorrow,Movie,Sci-Fi & Fantasy,2026,2026-04-12,United States,108 min,TV-PG
s1387,Project Tomorrow,Movie,Dramas,2026,2026-04-15,Germany,130 min,PG
s1388,Code Tomorrow,Movie,Romantic Movies,2026,2026-04-18,France,122 min,PG-13
s1389,Code Horizon,Movie,Action & Adventure,2026,2026-04-22,Australia,155 min,R
s1390,Project Horizon: Season 3,TV Show,Anime Series,2026,2026-04-25,Japan,3 Seasons,TV-MA
s1391,Project Horizon,Movie,Documentaries,2026,2026-04-28,Canada,114 min,R
s1392,Secrets of Tomorrow: Season 4,TV Show,Action & Adventure,2026,2026-05-02,France,4 Seasons,PG-13
s1393,Secrets of Horizon,Movie,Sci-Fi & Fantasy,2026,2026-05-05,United Kingdom,130 min,G
s1394,Chasing Horizon,Movie,Thrillers,2026,2026-05-08,Germany,128 min,TV-G
s1395,Project Horizon,Movie,Dramas,2026,2026-05-12,Brazil,145 min,PG-13
s1396,Secrets of Tomorrow,Movie,Dramas,2026,2026-05-15,India,159 min,PG-13
s1397,Project Tomorrow,Movie,Comedies,2026,2026-05-18,Japan,116 min,R
s1398,Project Tomorrow,Movie,Horror Movies,2026,2026-05-22,South Korea,134 min,R
s1399,Lost Tomorrow,Movie,Action & Adventure,2026,2026-05-25,France,125 min,PG-13
s1400,Chasing Tomorrow,Movie,Sci-Fi & Fantasy,2026,2026-05-28,Canada,110 min,PG
s1401,Code Tomorrow,Movie,Documentaries,2026,2026-06-01,Spain,104 min,R
s1402,The Last Horizon,Movie,Action & Adventure,2026,2026-06-02,Spain,113 min,TV-14
s1403,Shadow Tomorrow,Movie,Action & Adventure,2026,2026-06-03,United States,147 min,R
s1404,Lost Horizon,Movie,Sci-Fi & Fantasy,2026,2026-06-04,Canada,154 min,PG-13
s1405,Code Tomorrow,Movie,Comedies,2026,2026-06-05,United Kingdom,146 min,PG
s1406,Project Tomorrow,Movie,Sci-Fi & Fantasy,2026,2026-06-06,Japan,144 min,R
s1407,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2026,2026-06-07,South Korea,112 min,R
s1408,Code Tomorrow,Movie,Dramas,2026,2026-06-08,Canada,116 min,TV-14
s1409,Secrets of Tomorrow,Movie,Comedies,2026,2026-06-09,France,125 min,R
s1410,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2026,2026-06-10,Spain,158 min,TV-14
s1411,Secrets of Horizon,Movie,Sci-Fi & Fantasy,2026,2026-06-11,Australia,134 min,PG-13
s1412,Code Tomorrow,Movie,Documentaries,2025,2025-01-11,Mexico,122 min,PG-13
s1413,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-01-14,Australia,155 min,PG-13
s1414,Project Tomorrow,Movie,Thrillers,2025,2025-01-17,Brazil,151 min,TV-14
s1415,Lost Horizon,Movie,Sci-Fi & Fantasy,2025,2025-01-20,India,107 min,TV-Y
s1416,Secrets of Tomorrow,Movie,Comedies,2025,2025-01-23,Canada,142 min,PG-13
s1417,Code Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-01-26,France,110 min,PG
s1418,Code Tomorrow,Movie,Action & Adventure,2025,2025-01-29,Japan,116 min,R
s1419,Project Horizon,Movie,Sci-Fi & Fantasy,2025,2025-02-01,Spain,124 min,R
s1420,Project Tomorrow,Movie,Romantic Movies,2025,2025-02-04,South Korea,108 min,TV-MA
s1421,Lost Horizon,Movie,Action & Adventure,2025,2025-02-07,Germany,113 min,TV-14
s1422,Project Tomorrow: Season 4,TV Show,Anime Series,2025,2025-02-10,Japan,4 Seasons,TV-Y7
s1423,Lost Tomorrow,Movie,Action & Adventure,2025,2025-02-13,Canada,114 min,PG-13
s1424,Secrets of Tomorrow,Movie,Action & Adventure,2025,2025-02-16,Australia,128 min,G
s1425,The Last Horizon,Movie,Dramas,2025,2025-02-19,India,139 min,R
s1426,Chasing Tomorrow,Movie,Action & Adventure,2025,2025-02-22,Japan,117 min,PG
s1427,Lost Horizon,Movie,Documentaries,2025,2025-02-25,Brazil,104 min,R
s1428,Lost Horizon,Movie,Comedies,2025,2025-02-28,Mexico,125 min,R
s1429,Code Tomorrow,Movie,Dramas,2025,2025-03-03,France,154 min,PG-13
s1430,Secrets of Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-03-06,Spain,155 min,PG-13
s1431,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-03-09,South Korea,122 min,TV-G
s1432,Lost Horizon,Movie,Dramas,2025,2025-03-12,Canada,114 min,PG-13
s1433,Project Tomorrow: Season 3,TV Show,International TV Shows,2025,2025-03-15,South Korea,3 Seasons,TV-MA
s1434,Secrets of Tomorrow,Movie,Action & Adventure,2025,2025-03-18,United Kingdom,104 min,R
s1435,Lost Tomorrow,Movie,Action & Adventure,2025,2025-03-21,Australia,159 min,PG
s1436,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-03-24,Spain,129 min,TV-Y7
s1437,The Last Horizon,Movie,Comedies,2025,2025-03-27,France,104 min,TV-MA
s1438,Code Tomorrow,Movie,Action & Adventure,2025,2025-03-30,South Korea,142 min,PG-13
s1439,Secrets of Tomorrow,Movie,Horror Movies,2025,2025-04-02,Australia,158 min,TV-MA
s1440,Project Tomorrow,Movie,Dramas,2025,2025-04-05,Spain,110 min,PG
s1441,Lost Horizon: Season 4,TV Show,Anime Series,2025,2025-04-08,Japan,4 Seasons,TV-Y7
s1442,Project Tomorrow,Movie,Documentaries,2025,2025-04-11,United Kingdom,133 min,TV-PG
s1443,Midnight Tomorrow,Movie,Romantic Movies,2025,2025-04-14,Canada,124 min,PG-13
s1444,Secrets of Tomorrow,Movie,Dramas,2025,2025-04-17,Germany,122 min,TV-Y
s1445,Project Tomorrow,Movie,Action & Adventure,2025,2025-04-20,India,112 min,TV-14
s1446,Project Tomorrow,Movie,Documentaries,2025,2025-04-23,Mexico,99 min,G
s1447,The Last Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-04-26,United States,108 min,TV-PG
s1448,Project Tomorrow,Movie,Dramas,2025,2025-04-29,Germany,130 min,PG
s1449,Code Tomorrow,Movie,Romantic Movies,2025,2025-05-02,France,122 min,PG-13
s1450,Code Horizon,Movie,Action & Adventure,2025,2025-05-05,Australia,155 min,R
s1451,Project Horizon: Season 3,TV Show,Anime Series,2025,2025-05-08,Japan,3 Seasons,TV-MA
s1452,Project Horizon,Movie,Documentaries,2025,2025-05-11,Canada,114 min,R
s1453,Secrets of Tomorrow: Season 4,TV Show,Action & Adventure,2025,2025-05-14,France,4 Seasons,PG-13
s1454,Secrets of Horizon,Movie,Sci-Fi & Fantasy,2025,2025-05-17,United Kingdom,130 min,G
s1455,Chasing Horizon,Movie,Thrillers,2025,2025-05-20,Germany,128 min,TV-G
s1456,Project Horizon,Movie,Dramas,2025,2025-05-23,Brazil,145 min,PG-13
s1457,Secrets of Tomorrow,Movie,Dramas,2025,2025-05-26,India,159 min,PG-13
s1458,Project Tomorrow,Movie,Comedies,2025,2025-05-29,Japan,116 min,R
s1459,Project Tomorrow,Movie,Horror Movies,2025,2025-06-01,South Korea,134 min,R
s1460,Lost Tomorrow,Movie,Action & Adventure,2025,2025-06-04,France,125 min,PG-13
s1461,Chasing Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-06-07,Canada,110 min,PG
s1462,Code Tomorrow,Movie,Documentaries,2025,2025-06-10,Spain,104 min,R
s1463,The Last Horizon,Movie,Action & Adventure,2025,2025-06-13,Spain,113 min,TV-14
s1464,Shadow Tomorrow,Movie,Action & Adventure,2025,2025-06-16,United States,147 min,R
s1465,Lost Horizon,Movie,Sci-Fi & Fantasy,2025,2025-06-19,Canada,154 min,PG-13
s1466,Code Tomorrow,Movie,Comedies,2025,2025-06-22,United Kingdom,146 min,PG
s1467,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-06-25,Japan,144 min,R
s1468,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-06-28,South Korea,112 min,R
s1469,Code Tomorrow,Movie,Dramas,2025,2025-07-01,Canada,116 min,TV-14
s1470,Secrets of Tomorrow,Movie,Comedies,2025,2025-07-04,France,125 min,R
s1471,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-07-07,Spain,158 min,TV-14
s1472,Secrets of Horizon,Movie,Sci-Fi & Fantasy,2025,2025-07-10,Australia,134 min,PG-13
s1473,Code Tomorrow,Movie,Documentaries,2025,2025-07-13,Mexico,122 min,PG-13
s1474,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-07-16,Australia,155 min,PG-13
s1475,Project Tomorrow,Movie,Thrillers,2025,2025-07-19,Brazil,151 min,TV-14
s1476,Lost Horizon,Movie,Sci-Fi & Fantasy,2025,2025-07-22,India,107 min,TV-Y
s1477,Secrets of Tomorrow,Movie,Comedies,2025,2025-07-25,Canada,142 min,PG-13
s1478,Code Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-07-28,France,110 min,PG
s1479,Code Tomorrow,Movie,Action & Adventure,2025,2025-07-31,Japan,116 min,R
s1480,Project Horizon,Movie,Sci-Fi & Fantasy,2025,2025-08-03,Spain,124 min,R
s1481,Project Tomorrow,Movie,Romantic Movies,2025,2025-08-06,South Korea,108 min,TV-MA
s1482,Lost Horizon,Movie,Action & Adventure,2025,2025-08-09,Germany,113 min,TV-14
s1483,Project Tomorrow: Season 4,TV Show,Anime Series,2025,2025-08-12,Japan,4 Seasons,TV-Y7
s1484,Lost Tomorrow,Movie,Action & Adventure,2025,2025-08-15,Canada,114 min,PG-13
s1485,Secrets of Tomorrow,Movie,Action & Adventure,2025,2025-08-18,Australia,128 min,G
s1486,The Last Horizon,Movie,Dramas,2025,2025-08-21,India,139 min,R
s1487,Chasing Tomorrow,Movie,Action & Adventure,2025,2025-08-24,Japan,117 min,PG
s1488,Lost Horizon,Movie,Documentaries,2025,2025-08-27,Brazil,104 min,R
s1489,Lost Horizon,Movie,Comedies,2025,2025-08-30,Mexico,125 min,R
s1490,Code Tomorrow,Movie,Dramas,2025,2025-09-02,France,154 min,PG-13
s1491,Secrets of Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-09-05,Spain,155 min,PG-13
s1492,Lost Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-09-08,South Korea,122 min,TV-G
s1493,Lost Horizon,Movie,Dramas,2025,2025-09-11,Canada,114 min,PG-13
s1494,Project Tomorrow: Season 3,TV Show,International TV Shows,2025,2025-09-14,South Korea,3 Seasons,TV-MA
s1495,Secrets of Tomorrow,Movie,Action & Adventure,2025,2025-09-17,United Kingdom,104 min,R
s1496,Lost Tomorrow,Movie,Action & Adventure,2025,2025-09-20,Australia,159 min,PG
s1497,Project Tomorrow,Movie,Sci-Fi & Fantasy,2025,2025-09-23,Spain,129 min,TV-Y7
s1498,The Last Horizon,Movie,Comedies,2025,2025-09-26,France,104 min,TV-MA
s1499,Code Tomorrow,Movie,Action & Adventure,2025,2025-09-29,South Korea,142 min,PG-13
s1500,Secrets of Tomorrow,Movie,Horror Movies,2025,2025-10-02,Australia,158 min,TV-MA"""

# Parse raw string data into active Pandas DataFrame
df = pd.read_csv(io.StringIO(csv_data))

# Print structure verification checks directly within Colab
print(f"Dataset completely constructed with dimensions: {df.shape}")
print(f"Unique records confirmation: {df['show_id'].nunique()} unique entries.")

# Code block to automatically drop the complete file via the browser
try:
    filename = 'netflix_catalog_all_shows_500.csv'
    df.to_csv(filename, index=False)
    files.download(filename)
    print(f"\nSUCCESS: Browser download triggered for complete file: '{filename}'")
except Exception as e:
    print(f"\nError handling automatic pipeline downpour: {e}")

Dataset completely constructed with dimensions: (500, 9)
Unique records confirmation: 500 unique entries.

SUCCESS: Browser download triggered for complete file: 'netflix_catalog_all_shows_500.csv'

In [8]:
ratings = df
ratings.head()

,show_id,title,type,genres,release_year,date_added,country_origin,runtime_duration,rating
0,s1001,Wallace & Gromit: Vengeance Most Fowl,Movie,"Animation, Comedy",2025,2025-01-03,United Kingdom,82 min,G
1,s1002,Project Tomorrow,Movie,Documentaries,2025,2025-01-03,Canada,119 min,R
2,s1003,Echoes of Varanasi,Movie,Romantic Movies,2025,2025-01-04,India,136 min,TV-14
3,s1004,The Last Orion: Season 2,TV Show,Action & Adventure,2025,2025-01-07,Germany,2 Seasons,TV-PG
4,s1005,Code Eden,Movie,Comedies,2025,2025-01-08,Spain,157 min,PG-13

The current dataset `ratings` does not contain explicit user IDs or numerical ratings, which are necessary for building a user-item interaction matrix typically used in recommendation systems. The 'rating' column, for instance, describes content suitability (e.g., 'G', 'TV-14'), not user preferences.

To demonstrate the creation of a user-item matrix, we'll simulate user interaction data by:
1. Generating a set of random `userId`s.
2. Assigning synthetic numerical `rating`s (e.g., on a scale of 1 to 5) to shows.
3. Using `show_id` as the item identifier (like `movieId`).

In [10]:
# Generate synthetic user IDs and numerical ratings
num_users = 50
synthetic_users = [f'user_{i+1}' for i in range(num_users)]

# Create a list to store synthetic interaction data
interaction_data = []

for index, row in ratings.iterrows():
    show_id = row['show_id']
    # Assign random users to some shows, with random numerical ratings
    for _ in range(np.random.randint(1, 5)): # Each show gets 1-4 random ratings
        random_user = np.random.choice(synthetic_users)
        random_rating = np.random.randint(1, 6) # Ratings from 1 to 5
        interaction_data.append({'userId': random_user, 'show_id': show_id, 'numerical_rating': random_rating})

# Create a new DataFrame for synthetic user-item interactions
synthetic_interactions_df = pd.DataFrame(interaction_data)

# Merge synthetic interactions with the original show details (if needed for other columns)
# For the purpose of creating the user-item matrix, we primarily need userId, show_id, and numerical_rating

# Let's use this new dataframe as our 'ratings' for the matrix creation
ratings = synthetic_interactions_df.merge(df[['show_id', 'title']], on='show_id', how='left')

print("Synthetic 'ratings' DataFrame with userId and numerical_rating created:")
display(ratings.head())

Synthetic 'ratings' DataFrame with userId and numerical_rating created:

    userId show_id  numerical_rating                                  title
0  user_50   s1001                 4  Wallace & Gromit: Vengeance Most Fowl
1  user_12   s1001                 2  Wallace & Gromit: Vengeance Most Fowl
2  user_32   s1001                 4  Wallace & Gromit: Vengeance Most Fowl
3   user_1   s1001                 4  Wallace & Gromit: Vengeance Most Fowl
4  user_47   s1002                 4                       Project Tomorrow

In [11]:
def create_matrix(df):
    user_mapper = {uid: i for i, uid in enumerate(df['userId'].unique())}
    movie_mapper = {mid: i for i, mid in enumerate(df['show_id'].unique())}
    movie_inv_mapper = {i: mid for mid, i in movie_mapper.items()}

    user_index = df['userId'].map(user_mapper)
    movie_index = df['show_id'].map(movie_mapper)

    # Make sure to import csr_matrix from scipy.sparse
    from scipy.sparse import csr_matrix
    X = csr_matrix((df["numerical_rating"], (movie_index, user_index)),
                   shape=(len(movie_mapper), len(user_mapper)))
    return X, movie_mapper, movie_inv_mapper


X, movie_mapper, movie_inv_mapper = create_matrix(ratings)

user_item_matrix = ratings.pivot_table(
    index="title", columns="userId", values="numerical_rating")
print(user_item_matrix.iloc[:10, :5])

userId                               user_1  user_10  user_11  user_12  \
title
Avatar: The Last Airbender Season 2     NaN      NaN      NaN      NaN
Back in Action                          NaN      NaN      NaN      NaN
Black Mirror Season 7                   NaN      NaN      NaN      NaN
Chasing Grid                            NaN      NaN      NaN      NaN
Chasing Horizon                         5.0      4.0      4.0      4.5
Chasing Orion: Season 2                 NaN      NaN      NaN      NaN
Chasing Orion: Season 3                 NaN      NaN      NaN      NaN
Chasing Silence                         NaN      NaN      NaN      NaN
Chasing Tomorrow                        NaN      1.0      4.0      NaN
Chasing Tomorrow: Season 2              NaN      NaN      NaN      NaN

userId                               user_13
title
Avatar: The Last Airbender Season 2      1.5
Back in Action                           1.0
Black Mirror Season 7                    NaN
Chasing Grid                             NaN
Chasing Horizon                          NaN
Chasing Orion: Season 2                  NaN
Chasing Orion: Season 3                  NaN
Chasing Silence                          NaN
Chasing Tomorrow                         NaN
Chasing Tomorrow: Season 2               NaN

In [18]:
def recommend_similar(movie_title, df, X, movie_mapper, movie_inv_mapper, k=5):
    # Use 'show_id' instead of 'movieId'
    movie_id = df[df['title'] == movie_title]['show_id'].iloc[0]
    movie_idx = movie_mapper[movie_id]
    movie_vec = X[movie_idx]

    from sklearn.neighbors import NearestNeighbors
    model = NearestNeighbors(metric='cosine', algorithm='brute')
    model.fit(X)
    distances, indices = model.kneighbors(movie_vec.reshape(1, -1), n_neighbors=k + 1)

    neighbor_ids = [movie_inv_mapper[i] for i in indices.flatten()[1:]]
    # Use 'show_id' instead of 'movieId'
    recommendations = df[df['show_id'].isin(neighbor_ids)]['title'].unique()

    print(f"\nBecause you liked **{movie_title}**, you might also enjoy:")
    for rec in recommendations:
        print(f"- {rec}")

In [17]:
recommend_similar("Michael", ratings, X,
                  movie_mapper, movie_inv_mapper, k=5)

Because you liked **Michael**, you might also enjoy:
- Secrets of Tomorrow
- Project Tomorrow
- Lost Horizon
- Chasing Horizon